# Generated by Django 4.0.5 on 2022-06-10 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_remove_company_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='total_industries',
        ),
    ]
